runtime: python
service: img-similarity-v1
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    python_version: 3.7
resources:
    cpu: 1
    memory_gb: 4
    disk_size_gb: 16
readiness_check:
  app_start_timeout_sec: 1800
